### ISSUE TITLE
Support for topic conditions

### ISSUE THREAD

**Issue by peterjuras** [SimonMarquis/FCM-toolbox#7]
Hi!

Thanks for this great tool 👍 ! I wanted to ask whether [topic conditions](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging) (search for condition) are supported or there is plan to support them in the future.

I could also offer to do a pull request to enable this.

Best,
Peter

**Comment by SimonMarquis** [comment]
Hi,
Support for topics has been added in https://github.com/SimonMarquis/FCM-toolbox/commit/c8c4fac2e18a7592804193922444f976dda9a9b4
It's available on the android app in the overflow menu.
In the web app, you can send messages to topics instead of individual device token.
Though conditions are not supported yet on the web app.
Let me know if you found something suitable to offer on the web app.

**Comment by peterjuras** [comment]
Thanks for the quick reply. I would like to also have conditions available on the web app, to allow non-technical teams to send more advanced notifications from a website.

Is there a plan to add support for **topic conditions** on the website?

**Comment by SimonMarquis** [comment]
No, unfortunately there is no plan to add this option at the moment.

**Comment by peterjuras** [comment]
I see. Thanks for your quick reply! Would you be open to accepting pull requests that add this feature to the web app?

**Comment by SimonMarquis** [comment]
Yes, I'll definitely review this, and add it to the project if it fits nicely into the current style of the web app.
